version: '3'
services:
  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      database_url: 'root:password@tcp(db:3306)/db'
      listen_port: 8092
    ports:
      - '8092:8092'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: